env: JRUBY_OPTS=--debug
dist: trusty
language: ruby
cache: bundler
services:
  - postgresql
rvm:
  - jruby-9.2.9.0
  - 2.7.1
  - 2.6.5
  - 2.5.7
before_install:
  - sudo apt-get install -y libgl1-mesa-dev
  - gem update --system
  - gem install bundler
script: bundle exec rake build spec
