# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

# Reference environment variables: https://docs.github.com/en/actions/reference/environment-variables

name: Cosmos Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.7", "3.0", "3.1"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          working-directory: cosmos
      - name: Run tests
        run: bundle exec rake build spec
        working-directory: cosmos
        env:
          COSMOS_DEVEL: ${GITHUB_WORKSPACE}\cosmos
          COSMOS_REDIS_USERNAME: test
          COSMOS_REDIS_PASSWORD: testPassword
          COSMOS_MINIO_USERNAME: testMinio
          COSMOS_MINIO_PASSWORD: testMinioPassword
          COSMOS_SERVICE_PASSWORD: testService
          COSMOS_SR_REDIS_USERNAME: testRunner
          COSMOS_SR_REDIS_PASSWORD: testRunnerPassword
          COSMOS_SR_MINIO_USERNAME: testRunnerMinio
          COSMOS_SR_MINIO_PASSWORD: testRunnerMinioPassword
